//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouletteWebApi.LogicLayer.DataAccessLayer.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RouletteWebApi.LogicLayer.DataAccessLayer.Database.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.AddUser.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.GetOriginalBet.
        /// </summary>
        internal static string GetOriginalBet {
            get {
                return ResourceManager.GetString("GetOriginalBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.InsertBets.
        /// </summary>
        internal static string InsertBets {
            get {
                return ResourceManager.GetString("InsertBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.InsertPayout.
        /// </summary>
        internal static string InsertPayout {
            get {
                return ResourceManager.GetString("InsertPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.InsertRounds.
        /// </summary>
        internal static string InsertSpins {
            get {
                return ResourceManager.GetString("InsertSpins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.LoginUser.
        /// </summary>
        internal static string LoginUser {
            get {
                return ResourceManager.GetString("LoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.RetrieveSpins.
        /// </summary>
        internal static string RetrieveSpins {
            get {
                return ResourceManager.GetString("RetrieveSpins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.RetrivePayout.
        /// </summary>
        internal static string RetrivePayout {
            get {
                return ResourceManager.GetString("RetrivePayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.UpdateBalances.
        /// </summary>
        internal static string UpdateBalances {
            get {
                return ResourceManager.GetString("UpdateBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.ValidateUserExists.
        /// </summary>
        internal static string ValidateUserExists {
            get {
                return ResourceManager.GetString("ValidateUserExists", resourceCulture);
            }
        }
    }
}
